blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com
    about: Please see SECURITY.md in this repository and report vulnerabilities privately.