name: CI Bot - Build, Test, Report, Update

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci-bot:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # Setup
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest black

      # -------------------------
      # Checks
      # -------------------------
      - name: Run Lint Check
        id: lint
        run: flake8 backend tests || true

      - name: Run Tests
        id: tests
        run: pytest --maxfail=1 --disable-warnings -q || true

      - name: Check Build (syntax)
        id: build
        run: python -m py_compile backend/*.py || true

      # -------------------------
      # Update Docs with Author
      # -------------------------
      - name: Add Author Info
        run: |
          mkdir -p docs
          echo "## Author" > docs/AUTHORS.md
          echo "- Raja Muhammad Awais" >> docs/AUTHORS.md

          if ! grep -q "## Author" README.md; then
            echo -e "\n## Author\nRaja Muhammad Awais" >> README.md
          fi

      # -------------------------
      # Update License
      # -------------------------
      - name: Update LICENSE with Author
        run: |
          year=$(date +'%Y')
          if [ -f LICENSE ]; then
            if ! grep -q "Raja Muhammad Awais" LICENSE; then
              sed -i "s/Copyright (c) .*/Copyright (c) $year Raja Muhammad Awais/" LICENSE || true
            fi
          else
            echo "MIT License" > LICENSE
            echo "" >> LICENSE
            echo "Copyright (c) $year Raja Muhammad Awais" >> LICENSE
            echo "" >> LICENSE
            curl -s https://opensource.org/licenses/MIT | sed -n '/Permission is hereby granted/,/SOFTWARE./p' >> LICENSE
          fi

      # -------------------------
      # Auto Fix (if errors found)
      # -------------------------
      - name: Try Auto-Fix (format + lint)
        run: |
          echo "⚡ Attempting to auto-fix issues..."
          black backend tests || true
          flake8 backend tests || true

      # -------------------------
      # Commit changes into bot branch
      # -------------------------
      - name: Reset bot branch
        run: |
          git fetch origin
          git checkout -B ci-bot/update origin/main

      - name: Commit changes to ci-bot branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 CI Bot: fixes, license, author update"
          branch: ci-bot/update
          create_branch: true

      # -------------------------
      # Create Pull Request into main
      # -------------------------
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci-bot/update
          title: "🤖 CI Bot: Automated Fixes & Updates"
          body: |
            This PR was created automatically by the CI Bot.

            ### Changes
            - ✅ Lint/Tests checked
            - 📜 Author/License updated (Raja Muhammad Awais)
            - ⚡ Auto-fixes applied where possible

            ---
            ✅ CLA signed automatically by Raja Muhammad Awais
          labels: bot, automated-pr
          base: main
