name: CI - Lint, Test, Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort pytest

      - name: Lint (flake8)
        run: flake8 backend tests

      - name: Format check (black)
        run: black --check backend tests

      - name: Imports check (isort)
        run: isort --profile black --check-only backend tests

      - name: Unit tests
        run: pytest -q
        env:
          TF_ENABLE_ONEDNN_OPTS: "0"
          TF_CPP_MIN_LOG_LEVEL: "2"

  docker-build:
    runs-on: ubuntu-latest
    needs: python-ci
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: false
          tags: network-anomaly-backend:ci