name: Auto Version & Badges

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure VERSION file exists and bump version
        id: version
        run: |
          if [ ! -f VERSION ]; then
            echo "0.0.0" > VERSION
          fi
          current=$(cat VERSION)
          IFS='.' read -r major minor patch <<< "$current"
          patch=$((patch+1))
          new_version="$major.$minor.$patch"
          echo "$new_version" > VERSION
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Generate Badges
        run: |
          echo "![Build](https://github.com/${{ github.repository }}/actions/workflows/build.yml/badge.svg)" > badges.md
          echo "![Tests](https://github.com/${{ github.repository }}/actions/workflows/test.yml/badge.svg)" >> badges.md
          echo "![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)" >> badges.md
          echo "![Python](https://img.shields.io/badge/Python-3.11-blue.svg)" >> badges.md
          echo "![Version](https://img.shields.io/badge/Version-${{ steps.version.outputs.new_version }}-blue.svg)" >> badges.md

      - name: Update README with badges
        run: |
          # Remove old badges between markers
          sed -i '/<!-- badges:start -->/,/<!-- badges:end -->/d' README.md || true
          # Insert fresh badges
          (echo "<!-- badges:start -->"; cat badges.md; echo "<!-- badges:end -->"; cat README.md) > README_new.md
          mv README_new.md README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Auto-bump version & update badges"
          branch: main
